### ISSUE TITLE
Broken password prompting with multiple repositories

### ISSUE THREAD

**Issue by iluetkeb** [dirk-thomas/vcstool#124] opened 2020-04-17 10:12 UTC
When VCS needs a password to access a repository, it will ask for it interactively.

Unfortunately, when there are several repositories requiring a password, it will ask for all of them *at the same time*. Needless to say, this doesn't work ;-) The password entered on the first repository will be used as the username for the second, and so on.

Please change this so that the credentials are asked sequentially.

**Comment by christophebedard** [comment] 2020-04-17 11:41
Duplicate of #23.

You can use `--workers 1` as a workaround :P

**Comment by iluetkeb** [comment] 2020-04-17 12:13
Aha. This doesn't seem to have made it into the docs ;-)

**Closed** 2020-04-17 13:20 UTC

**Comment by dirk-thomas** [comment] 2020-04-17 15:22
> This doesn't seem to have made it into the docs ;-)

Actually it is documented since #119: https://github.com/dirk-thomas/vcstool/blob/master/README.rst#parallelization-and-stdin

**Comment by iluetkeb** [comment] 2020-04-17 15:27
My bad! Thanks for the info Dirk.
