### ISSUE TITLE
importing using ssh with version key specified leads to ValueError

### ISSUE THREAD

**Issue by kevinshchang** [dirk-thomas/vcstool#151] opened 2020-06-15 16:30 UTC
`Invocation of command 'import' on client 'git' failed: ValueError: need more than 1 value to unpack (/usr/lib/python2.7/dist-packages/vcstool/clients/git.py:477)`

Line in question is 
`            hash_, ref = line.split(None, 1)`

public repos imported using https and version seem to import correctly, but importing repos with ssh and version is leading me to the error. Importing repos with ssh and no version seems to work correctly. 

vcs version: 0.2.10
python version: 2.7.12

**Comment by dirk-thomas** [comment] 2020-06-15 20:58
Unfortunately I can't reproduce the problem. Maybe you can share more information about your `.repos` files and/or how you authenticate with the private repo?

Some debugging information might also be helpful. Can you please edit the file `git.py` and add some debug information and share the output from your case:
* insert at line 475: `print(result['output'])`
* between the `for` loop and the line calling `split` insert: `print(line)`

**Comment by kevinshchang** [comment] 2020-06-15 21:35
Just did some more testing. We have a print that occurs when we clone internally before the hashes and refs, so result['output'] looks like
```
-------------
A whole bunch of text
-------------
hash          ref
```
This breaks the expected sequence of all hashes and references

**Comment by dirk-thomas** [comment] 2020-06-15 22:30
> We have a print that occurs when we clone internally before the hashes and refs,

Where is that coming from? Can you please provide some more context or an example to illustrate?

**Comment by kevinshchang** [comment] 2020-06-16 14:05
Its the ssh banner generated whenever a SSH connection is made to the server (even via git).
Something like https://www.tecmint.com/protect-ssh-logins-with-ssh-motd-banner-messages/

I've fixed the issue on my end by setting the LogLevel of the host to QUIET in my ssh config file.

Perhaps debugging documentation should be added, or some try/catch/pass in the loop to avoid failure on a ssh banner from the server?

**Comment by dirk-thomas** [comment] 2020-06-16 15:51
> I've fixed the issue on my end by setting the LogLevel of the host to QUIET in my ssh config file.

Please try the patch proposed in #154 and comment if it resolves the problem for you (with your config change reverted).

**Comment by kevinshchang** [comment] 2020-06-16 17:33
The fix works! 

In our case, each line of the banner does not start with '#', and looks like what I posted above, with literally a line of
-----------------
on top and below of a lot of text describing security and privacy agreements, which also means for our case, the statement to catch '#' does nothing, but the problem is still solved by the try except. (I can vcs import even when I delete the lines to catch if it starts with '#') 

I believe in general, these banners can be whatever the system administrators want them to be, so I'm not sure if there is a clear pattern to distinguish them.

**Comment by dirk-thomas** [comment] 2020-06-16 18:11
Thanks for helping debug this and checking the patch. This will be addressed in the upcoming patch release.

**Closed** 2020-06-16 18:12 UTC
Labels: bug
