### ISSUE TITLE
Cant clone with commit hash

### ISSUE THREAD

**Issue by MaxandreOgeret** [dirk-thomas/vcstool#161] opened 2020-07-06 14:20 UTC
Hello, since I updated the module my repo file fails when I import it, with this error message : 

Could not determine ref type of version: 67a93bcfee4f7e9e39e79f138ecadbba5c8392b7	refs/keep-around/67a93bcfee4f7e9e39e79f138ecadbba5c8392b7

Of course the commit exists  and I can clone it with command line

Worked perfect before updating. Thanks

**Comment by dirk-thomas** [comment] 2020-07-06 15:46
> since I updated the module ...

What version did you update too?

Please share a `.repos` file which reproduces the problem.

**Comment by dirk-thomas** [comment] 2020-07-10 16:33
I am going to close this ticket for now due to no further response and since a unit test covers this exact use case and passes fine. Please feel free to comment on the closed ticket with the requested information and the ticket can be reopened if necessary.

**Comment by iwannatto** [comment] 2020-07-20 01:56
I encountered the same problem.

excerpt from my .repo
```
  vendor/mrt_cmake_modules:
    type: git
    url: git@github.com:KIT-MRT/mrt_cmake_modules.git
    version: 8bba2d3d7c6e62f3dcc46d85c3d1cd128b30734e
```

error mesage:
```
=== src/vendor/mrt_cmake_modules (git) ===
Could not determine ref type of version: 8bba2d3d7c6e62f3dcc46d85c3d1cd128b30734e	refs/keep-around/8bba2d3d7c6e62f3dcc46d85c3d1cd128b30734e
```

This occurred in pip3-installed v0.2.11 and v0.2.10 and didn't occur in v0.2.9.
I heard that someone didn't encounter this even in v0.2.11, so this problem may depend on each environment to some extent...

**Comment by dirk-thomas** [comment] 2020-07-20 04:57
@iwannatto Thank you for the additional information. I was able to reproduce the problem and implement a fix. Please see #163 and consider giving it a try to confirm it works for you too.

**Closed** 2020-07-20 18:49 UTC
Labels: bug
