### ISSUE TITLE
export fails with multiple remotes

### ISSUE THREAD

**Issue by NikolausDemmel** [dirk-thomas/vcstool#10] opened 2015-02-26 10:53 UTC
With two remotes `foo` and `bar`:
```
$ vcs export
Could not determine remote url: error: invalid key (newline): remote.foo
bar.url
```

**Comment by dirk-thomas** [comment] 2015-02-26 12:09
Duplicate of #8.

**Closed by dirk-thomas** 2015-02-26 12:09 UTC

**Comment by jbohren** [comment] 2015-02-26 13:59
@NikolausDemmel Feel free to try out my `fix-git-multiple-remotes` branch, which handles this situation: https://github.com/jbohren-forks/vcstool/tree/fix-git-multiple-remotes
